### ISSUE TITLE
hash in test_name of is() / ok() printed as backslash-hash

### ISSUE THREAD

**Issue by pryrt** [Test-More/test-more#709] opened 2016-08-18 19:19 UTC
I tried using a hash / number sign ('#') in the `$test_name` parameter to an `is()` or `ok()` call

    perl -MTest::More=tests,2 -e "$str='A#A'; is( 1, 1, 'is:'.$str); ok(1, 'ok:'.$str); diag('diag:'.$str); note('note:'.$str)"

and was suprised to discover it was printed with a preceding backslash ('\\#').

    1..2
    ok 1 - is:A\#A
    ok 2 - ok:A\#A
    # diag:A#A
    # note:A#A

Is this intentional, or a bug?

**Comment by exodist** [comment] 2016-08-18 19:35
it is intentional

the TAP standard dictates that an 'ok' line may have a directive at the end denoted by the '#' character. as such '#' is technically illegal in a test name/description.

Test::Builder, which is used by Test::More prefixes # with \ to escape it. Test2 on the other hand completely forbids '#'.

both of these have issues, Test::Harness for example will double escape the symbol when Test::Builder escapes it. On the other hand some people are having problems with the fact that Test2 simply forbids it.

anyway for now I am closing this ticket as not a bug. changing the way Test::Builder does this is out of the question as that would be a breaking change regardless of what change we make.

Test2 is another story, we can and probably will change the behavior, but have not yet decided what the best fix is.

**Closed** 2016-08-18 19:35 UTC

**Comment by pryrt** [comment] 2016-08-18 19:46
Ah, makes sense.  Since not every user of Test::More (or Test::Simple or Test::Builder) is intimate with the underlying TAP standard, it might be nice to have that mentioned somewhere in the POD for one or more of those modules.  Though I'm not sure where the best place in the documentation it would go.

Anyway, thanks for answering so promptly.

**Comment by exodist** [comment] 2016-08-18 19:59
https://github.com/Test-More/test-more/issues/710  fyi
