### ISSUE TITLE
is() diagnostic output can get confused about \n

### ISSUE THREAD

**Issue by leonerd** [Test-More/test-more#731] opened 2016-10-24 20:46 UTC
If the input string contains both actual linefeeds (`\n`) and literal backslash-n (`\\n`) sequences, the output is confusing:

    $ perl -MTest::More -E 'is("\n - \n", "\\n - \n")'
    not ok 1
    #   Failed test at -e line 1.
    #          got: "\n - \n"
    #     expected: "\n - \n"

For reference:

    $ perlmodversion Test::More
    1.001014

**Comment by exodist** [comment] 2016-10-25 03:57
The problem with fixing this is that it could easily break downstream things that test TAP using Test::Builder::Tester or Test::Tester.

I am in favor of making it render literal '\n' as '\\n' leaving a regular newline as \n. But lots of testing will be needed.

**Comment by exodist** [comment] 2016-10-26 03:28
just decided to try your example:

`
perl -MTest::More -E 'say $Test::More::VERSION; is("\n - \n", "\\n - \n")'
1.302059
not ok 1
#   Failed test at -e line 1.
#          got: '
#  - 
# '
#     expected: '\n - 
# '
# Tests were run but no plan was declared and done_testing() was not seen.
`

The output here looks nothing like the one you present. I am going to revert to the old Test::More you are using to see if I can reproduce.

**Comment by exodist** [comment] 2016-10-26 03:30
```
perl -MTest::More -E 'say $Test::More::VERSION; is("\n - \n", "\\n - \n")'
1.001014
not ok 1
#   Failed test at -e line 1.
#          got: '
#  - 
# '
#     expected: '\n - 
# '
# Tests were run but no plan was declared and done_testing() was not seen.
```

Looks like the old version also has this output. This makes me wonder why your output is different.

**Comment by exodist** [comment] 2016-10-27 03:33
I am going to close this ticket for now. Please re-open with additional information if this is actually a Test::Builder bug. I suspect you are using a modified version, or something extra that renders newlines in a different way.

**Closed by exodist** 2016-10-27 03:33 UTC
Labels: Cannot Reproduce
