### ISSUE TITLE
"read Test::Tutorial" link broken on Test::Simple doc page

### ISSUE THREAD

**Issue by dP14EOOgMDg** [Test-More/test-more#604] opened 2015-09-22 15:22 UTC
On the doc page for Test::Simple, http://perldoc.perl.org/Test/Simple.html, the following admonition has a broken link:

    If you are unfamiliar with testing read Test::Tutorial first!

The link for the test tutorial is broken.  it points to

     http://perldoc.perl.org/Test/Tutorial.html

**Comment by haarg** [comment] 2015-09-22 16:10
This looks like an issue with perldoc.perl.org, since the dist (and what is packaged with perl) includes a Test::Tutorial pod file.

It would however probably be good to have Test::Tutorial listed in the provides data so that it gets listed in 02packages.  That won't help with perldoc.perl.org though, since it doesn't use META files (and they aren't even included with perl core).

**Comment by exodist** [comment] 2016-05-03 19:20
not a bug on our end, closing.

**Closed by exodist** 2016-05-03 19:20 UTC
