### ISSUE TITLE
DAMS/PerlIO-via-Timeout-0.32.tar.gz fails with 1.302013_008

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#628] opened 2016-01-10 22:46 UTC
Seems to have started with _006

Good night,

**Comment by exodist** [comment] 2016-01-11 23:31
Looks like the problem is that a recent change caused is() to change the value of '$!'. Perl makes no guarantees about $! if it is not used immediately, but Test::More works very hard to keep from squashing it. I will fix this on Test::More's end.

**Comment by exodist** [comment] 2016-01-12 00:38
Fixed in latest release (_009)

**Closed by exodist** 2016-01-12 00:38 UTC
Labels: Blocking Stable, Bug, Test-Stream
