### ISSUE TITLE
Test2 breaks forkprove when Test::More is loaded with -M

### ISSUE THREAD

**Issue by wolfsage** [Test-More/test-more#659] opened 2016-05-10 18:19 UTC
This:

        forkprove -MTest::More t/

breaks with latest Test::Simple, but used to work fine.

**Comment by exodist** [comment] 2016-05-10 18:22
My *hunch* is that the fact that Test2 adds support for forking/threading the problem is that the parent PID is being recorded as the primary. In this case each test that runs is confused thinking it is a child. The easiest solution is to have forkprove blacklist Test::Builder. Alternatively it can call reset on the singleton post-fork.

This is all a hunch of course, I will have to look into it to be sure.

**Comment by exodist** [comment] 2016-05-10 18:26
https://github.com/miyagawa/forkprove/issues/4

Looks like it is already known to be a bad idea to preload Test::Builder with forkprove.

**Comment by Leont** [comment] 2016-05-16 16:32
> The easiest solution is to have forkprove blacklist Test::Builder.

That pretty much means blacklisting anything that uses Test::Builder, which may not be feasible.

**Comment by exodist** [comment] 2016-05-16 16:41
The root problem here is this:

Test::Builder initializes its singleton when the module is loaded. It does this in an initialization statement for a package variable, so it cannot be avoided via require or non-importing use(). This action records the current pid, and the thread id for use in comparisons down the line.

We cannot change this behavior because there are a lot of things that depend on the singleton being initialized here as opposed to import().

However, we might be able to get something close. I can add an ENV var, when set the env var can prevent the early initialization of the singleton. ForkProve could set this env var. To avoid breaking things though it would then need to initialize the singleton itself (calling Test::Builder->new) post-fork before running the tests.

**Comment by exodist** [comment] 2016-05-16 16:45
Just did a quick check. if I add the env var and run forkprove with it then the problem appears to go away, the things that are broken are things that break from $Test::Builder::Test not yet being the singleton

**Comment by exodist** [comment] 2016-05-16 16:49
hmm, reading the forkprove source it looks like it already resets the singleton if it is present, which means this actually might be easier to solve then I expected. looking into it.

**Comment by exodist** [comment] 2016-05-16 20:30
https://github.com/Test-More/test-more/pull/672

**Comment by exodist** [comment] 2016-05-16 20:30
https://github.com/miyagawa/forkprove/pull/13

**Comment by exodist** [comment] 2016-05-18 22:01
Fixed in latest -TRIAL release

**Closed** 2016-06-01 14:07 UTC
