### ISSUE TITLE
Forking daemon during test hangs exit from prove

### ISSUE THREAD

**Issue by Deracination** [Test-More/test-more#868] opened 2020-08-16 23:59 UTC
Test::More, Test2 version 1.302177

prove'ing a test which forks a daemon process will never exit until the daemon is killed.

This is a bit of a problem as I use a function in our test suite to restart some daemons if code has changed. This is no longer usable since the first test never exits.

Example: with `prove` this hangs until the sleep ends but exits immediately when run with `perl`

`
use Test::More;
system('sleep 5000 &');
`

**Comment by exodist** [comment] 2020-08-17 00:32
You may want to also open an issue on Test::Harness (prove). If the code works fine on perl, but fails in prove then it may be a prove issue. I am not ruling out a Test-Simple issue, and will investigate when I have a moment.

**Comment by exodist** [comment] 2020-08-17 05:00
This appears to happen with prove and yath. If you run it with perl it does appear to exit immediately, but a `ps` will show you that your perl did not actually exit, it is left as a zombie. I do not think this is an issue with Test::More, Prove, or Yath.

I will also point out that the same exact thing happens if you remove the 'use Test::More' and just have it call `system(sleep 5000)`.

I may be wrong in my understanding of signals, but I do not believe the sigchld will be sent by the zombie until the sleep returns. As such waitpid will not return. a good harness will use waitpid on the process it spawns, which is why prove/yath wait. The shell has its own process management, but the fact is the sleep is still running even thought he shell returned.

I think ultimately the bug is that you are "starting a daemon", but not actually starting a daemon, you are just spawning a child process. There is a difference. https://metacpan.org/pod/Proc::Daemon might be able to help you. Here is some more details: http://world.std.com/~swmcd/steven/tech/daemon.html.

Ultimately I do think everything here is working as desired. And no Test::* code has anything to do with the behavior you are seeing. A non-perl harness in place of prove would have the same issue. I think your tests need to be fixed to manage processes/spawn daemons more correctly.

**Comment by exodist** [comment] 2020-08-17 05:08
Switching the discussion over to https://github.com/Perl-Toolchain-Gang/Test-Harness/issues/99  for simplicity.

**Comment by exodist** [comment] 2020-08-18 02:06
As per conclusion on the other page, closing this as not a bug.

**Closed by exodist** 2020-08-18 02:06 UTC
