### ISSUE TITLE
'like' does not seem to be working anymore

### ISSUE THREAD

**Issue by moezhirani** [Test-More/test-more#630] opened 2016-01-21 20:39 UTC
I am running a test like following :

like($self->driver->get_current_url,qr/\/xxxxx\/xx\/\d+/,"Landed on right page");

However, test::more fails with the following:

```perl
not ok 17 - Landed on right page

#   Failed test 'Landed on right page'
#   at /home/autotest/local-lib/lib/perl5/Test/More.pm line 420.
#   (in Test::LandOnRightPage->b_test)
#     'qr/xxxxx\/xx\/\d+/' doesn't look much like a regex to me.
```

This test used to pass last release , but is suddenly breaking . I am not sure why it is not seen as a 'valid regex' anymore. Can you please help me out ?

I am using Test::More version '1.001003'

**Comment by kentfredric** [comment] 2016-01-21 21:11
Looking at the source of Test::More, I suspect the line of code is not:
```perl
  like($self->driver->get_current_url,qr/\/xxxxx\/xx\/\d+/,"Landed on right page");
```
But is instead
```perl
  like($self->driver->get_current_url,'qr/\/xxxxx\/xx\/\d+/',"Landed on right page");
```

The difference is very subtle. But if you can provide a .t file that replicates the issue, that'd be helpful.

Attached is a perl test that demonstrates a failure occurring the same as yours, in conjunction with doing it in a way that doesn't fail.

[re.t.txt](https://github.com/Test-More/test-more/files/99894/re.t.txt)


( Interested source divers should check :  https://metacpan.org/source/EXODIST/Test-Simple-1.001014/lib/Test/Builder.pm#L1417-1495 , and this is a fine example of why attempts to "clean up" stack traces can obfuscate problem solving, because even though where the problem is occurring is being correctly reported ... it doesn't communicate what so ever why the problem is occurring )

**Comment by exodist** [comment] 2016-01-21 21:16
I agree with kentnl, mostly. But, assuming for a moment that it is a bug, I also notice that you are using 1.001003. The current on cpan is Test-Simple-1.001014, could you please test on that?  I can't re-release 1.001003, so if it has been fixed in a newer version there is nothing left to do.

Looking at history, it seems the jump from 1.001002 to 1.001003 only had documentation changes

**Comment by moezhirani** [comment] 2016-01-21 21:27
Thanks very much ! I realize the problem is with the quote. ( 'qr/regex' vs qr/regex/)

It was failing because I had my regexes in a config file and was testing by reading the regex from the config file. I suppose I cannot do this ?

Here is an example:

regex_test.t:
```perl
use YAML::Tiny;
use Test::More;
plan tests => 1;

my $val = "grass/sun/55";
my $yaml = YAML::Tiny->read('config.yml');

my $cfg = $yaml->[0];
my $regex = $cfg->{my_regex};

like($val,$regex,"regex match test success!");

done_testing;
1;

```

config.yml

```yml
---
my_regex: qr/grass\/sun\/\d+/

```

If I run , perl regex_test.t , it fails with the error I described originally. If I dont use the config file, and place the regex directly in the like statement without the quotes, it works.

**Comment by kentfredric** [comment] 2016-01-21 21:29
Leaving out the "qr" on the front and just using the string `"/grass\/sun\/d+/"` should work because of : https://metacpan.org/source/EXODIST/Test-Simple-1.001014/lib/Test/Builder.pm#L1430-1431

**Comment by kentfredric** [comment] 2016-01-21 21:31
Though I should point out, you probably don't need to escape the `/` characters, because escaping is only needed when you're escaping a quoting construct. `/` is not itself a metachar, so:
```perl
   qr{grass/sun/\d+} == qr/grass\/sun\/d+/
```

**Comment by exodist** [comment] 2016-01-21 21:34
You can also eval it:

like($thing, eval $quoted_qr, "blah");

**Comment by kentfredric** [comment] 2016-01-21 21:35
I would have suggested eval myself, but its only safe if you can guarantee what "$quoted_qr"  is. Blindly evaling data from external sources who aren't you is not something I can advocate.

**Closed by exodist** 2016-01-21 21:34 UTC

**Comment by moezhirani** [comment] 2016-01-21 21:53
Thank you for all your help Kent and Chad !!! The quick responses are much appreciated !

**Comment by karenetheridge** [comment] 2016-01-21 22:02
I would have just done  `like(..., qr/$string_pattern_from_file/, ...)`

**Comment by karenetheridge** [comment] 2016-01-21 22:03
I would have just done:  `like(..., qr/$string_pattern_from_file/, ...)`
