### ISSUE TITLE
explain() is passing along scalar context to its arguments

### ISSUE THREAD

**Issue by karenetheridge** [Test-More/test-more#559] opened 2015-04-05 02:58 UTC
Here is a reproduction case. This is with version 1.001014.

```
use strict;
use warnings;

use Test::More;

# correct (prints a hashref):
diag "GOT:\n", explain({ key => 'value' });

# incorrect ((prints 1):
diag "GOT:\n" . explain({ key => 'value' });

__END__
# GOT:
# {
#   'key' => 'value'
# }
# GOT:
# 1
```

**Comment by exodist** [comment] 2015-04-05 19:48
Will fix next time I am able to sit down and look at it.

--------- 

Unrelated to fixing it, but still amusing:

Nice find. It also add fuel to the fire over explain that returns string and explain that prints for you. The fact that this bug has gone unnoticed for so long means people probably aren't assigning the return to a string and instead always print it.

History: Ovid first wrote explain in one of his tools, it just directly prints. Then Test::More took the idea and used the same name, but made it return the string for flexibility. This kind of shows that the flexibility is not utilized much in the wild since it is pretty broken.

That said I still don't think we can normalize the behavior between the 2 dists since either one changing would break backcompat.

**Comment by karenetheridge** [comment] 2015-04-05 20:12
> This kind of shows that the flexibility is not utilized much in the wild since it is pretty broken.

There are 48 pages of results for people combining the explain with another string: http://grep.cpan.me/?q=diag+.%2Bexplain -- this works fine when using a list, just not as a string concat (whereas `print` behaves the same either way).

**Comment by karenetheridge** [comment] 2015-04-05 20:14
Also lots of results for capturing the `explain` in a string: http://grep.cpan.me/?q=%3D\s*explain

**Comment by exodist** [comment] 2015-04-05 21:12
Hmm, with all those examples of people using it that way I actually need to reconsider if this is a bug. If that many people are using it that way, and likely aware of the context, then I need to be sure nobody relies on the current behavior. I also need to look at ticket archives to see if anyone reported it and had it closed as not a bug do to it being a desired or documented behavior.

I cannot think of any reason a sane person would want this context dependent behavior for this function, but I have been surprised before and I would not be surprised if there was someone just as eager to point out sane reasons for this behavior as you were to correct my mistake in my initial reply :-).

**Comment by exodist** [comment] 2015-04-05 21:14
https://metacpan.org/pod/Test::More#explain

It is documented that it returns a list of strings. And there is nothing int he document implying that it will return a single string when used in scalar context (there are no scalar context examples at all). As such I am once again thinking this may not be a bug, but rather a feature request.

**Comment by exodist** [comment] 2015-04-06 03:46
What would be the least surprising behavior that using explain in scalar context could have, concatenate all the strings? Return the first string? or what it does now, return the count of string? Also is there any reasonable and sane reason someone might want it to return the number of strings?

**Comment by karenetheridge** [comment] 2015-04-06 16:17
I expected it to return all the strings, so that the caller can manipulate
these strings as desired (e.g. send them to a diag or print). Indeed, you
said that this is what is documented:

> It is documented that it returns a list of strings.

This can be achieved easily by prefacing the map with `()= `.

**Comment by shadowcat-mst** [comment] 2015-04-06 20:50
21:26 <@mst> I think that in hindsight it would've been nice to have explain 
             only take a single argument
21:26 <@mst> and let people use map
21:26 <@mst> but now it's been documented as being\
21:26 <@mst> my @strings = explain @things;
21:27 <@kentnl> Yeh :/. People (myself included) are so inclined to just assume 
                its sugar syntax for Data::Dumper::Dumper
21:27 <@mst> I don't think 'fixing' is actually a good idea, and that the '1' 
             return in scalar context, while confusing, is going to be less 
             confusing when it goes wrong than most alternatives
21:27 <@mst> notably wantarray DWIM will lead people to thing it's 
             scalar->scalar and make the param() mistake
21:28 <@mst> we could, however, add an explain_one
21:28 <@mst> so you can also do
21:28 <@mst> my $string = explain_one $thing;

**Comment by exodist** [comment] 2016-05-03 19:24
After re-reading this bug I suspect there is nothing to do here. Changing Test::More is a bad idea. Test2 tools do not currently have an explain, and I do not intend to add one (though anyone is free to write one).

**Closed by exodist** 2016-05-03 19:24 UTC
Labels: Bug, Discuss
