### ISSUE TITLE
"Use of uninitialized value $indent in concatenation (.) or string at C:/strawberry163/perl/lib/Test/Builder.pm line 1816."

### ISSUE THREAD

**Issue by karenetheridge** [Test-More/test-more#553] opened 2015-03-13 17:44 UTC
This is in Test::Builder 1.001002:

http://www.cpantesters.org/cpan/report/6aaff5eb-6bf5-1014-9883-5e52e8ef0cfb

**Comment by exodist** [comment] 2015-03-13 18:11
Can we reproduce with 1.001014 (most recent stable) or with the dev releases?

**Comment by karenetheridge** [comment] 2015-03-14 00:16
The same error can be seen under 0.98: http://www.cpantesters.org/cpan/report/7d449260-c9aa-11e4-a30e-d018909b15a0

Also under Test::More 0.98:
Can't use an undefined value as a symbol reference at C:/strawberry180/perl/lib/Test/Builder.pm line 1759.
http://www.cpantesters.org/cpan/report/2268b274-6bfb-1014-abb9-be0fe5e177bd

http://matrix.cpantesters.org/?dist=Test-NewVersion+0.003

**Comment by karenetheridge** [comment] 2015-03-14 00:17
Even if the issue is gone in newer versions, I'd like to understand what the problem is, so I know what minimum version of Test::More to require.

**Comment by exodist** [comment] 2015-03-14 16:07
I don't know of it is gone or not. I was asking if you did. It is a strange issue, the variable in question should always be set to an empty string if nothing else based on how the singleton initializes, even back to the first version the issue was reported on.

I was wondering if it was reproducible on the latest stable cause If not a bisect should give us what we need. If the latest stable does still have the problem we will need a simple way to reproduce the issue and then look into it.

**Comment by karenetheridge** [comment] 2015-03-18 19:29
I haven't been able to reproduce this on any system, so I am unable to perform any bisection so far to narrow down the problem.

It isn't restricted just to windows though - there was a linux failure as well.

**Comment by exodist** [comment] 2015-03-23 23:16
I cannot reproduce either, gonna bump to lower priority until we find a way to reproduce.

**Comment by exodist** [comment] 2016-05-03 19:26
Closing this, the code that causes the problem has long since been reverted, rewritten, etc.

**Closed by exodist** 2016-05-03 19:26 UTC
Labels: Low Priority
