### ISSUE TITLE
Intermittent "Attempt to free unreferenced scalar" errors using _109

### ISSUE THREAD

**Issue by dagolden** [Test-More/test-more#589] opened 2015-04-29 19:36 UTC
When testing v0.708.0.0 of [MongoDB](http://p3rl.org/MongoDB), I get intermittent errors like this:

```
t/collection.t ......... 124/? Attempt to free unreferenced scalar: SV 0x7fa691b1e270,
 Perl interpreter: 0x7fa690801200 during global destruction.
```

It doesn't happen on all test files or even all test runs.  I believe it was happening on an older dev as well (posssibly _108, but I lost track between upgrades/downgrades).

Downgrading to the stable Test::More appears to prevent this from occurring.  I have not seen it in over a dozen test run, whereas with the dev Test::More, I've been seeing the error within 2 to 5 runs of "make test".

perl -V for reference:
```
Summary of my perl5 (revision 5 version 20 subversion 2) configuration:
   
  Platform:
    osname=darwin, osvers=14.1.0, archname=darwin-thread-multi-2level
    uname='darwin metis.local 14.1.0 darwin kernel version 14.1.0: mon dec 22 23:10:38 pst 2014; root:xnu-2782.10.72~2release_x86_64 x86_64 '
    config_args='-Dprefix=/Users/david/.plenv/versions/20.2t -de -Dusedevel -Dusethreads -Dman1dir=none -Dman3dir=none -A'eval:scriptdir=/Users/david/.plenv/versions/20.2t/bin''
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/opt/local/include',
    optimize='-O3',
    cppflags='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/opt/local/include'
    ccversion='', gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -fstack-protector -L/usr/local/lib -L/opt/local/lib'
    libpth=/usr/local/lib /Library/Developer/CommandLineTools/usr/bin/../lib/clang/6.0/lib /Library/Developer/CommandLineTools/usr/lib /usr/lib /opt/local/lib
    libs=-lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-ldl -lm -lutil -lc
    libc=, so=dylib, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector'


Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                        PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP
                        PERL_NEW_COPY_ON_WRITE PERL_PRESERVE_IVUV
                        PERL_USE_DEVEL USE_64_BIT_ALL USE_64_BIT_INT
                        USE_ITHREADS USE_LARGE_FILES USE_LOCALE
                        USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
                        USE_REENTRANT_API
  Built under darwin
  Compiled at Feb 18 2015 03:44:00
  %ENV:
    PERL_EXTUTILS_AUTOINSTALL="--defaultdeps"
  @INC:
    /Users/david/.plenv/versions/20.2t/lib/perl5/site_perl/5.20.2/darwin-thread-multi-2level
    /Users/david/.plenv/versions/20.2t/lib/perl5/site_perl/5.20.2
    /Users/david/.plenv/versions/20.2t/lib/perl5/5.20.2/darwin-thread-multi-2level
    /Users/david/.plenv/versions/20.2t/lib/perl5/5.20.2
    .
```

**Comment by exodist** [comment] 2015-05-01 21:47
I was able to boil the issue down to a fairly simple test-script: https://gist.github.com/exodist/ef08a3c406d98c1bb618 which is able to reproduce the problem sometimes. XDG has a slightly different version, but in both cases the key part is this:

ok(1);
my ($index) = grep { $_->{name} eq 'foo' } $coll->get_indexes;
ok(1);

The first ok is used to get some state into the system, if the state is not there the problem does not occur, or occurs too infrequently to measure. Ending the test right after the first ok also never seems to reproduce the issue.

The second line gets a variable generated deep inside the mongodb code, and I have been treating it like a black box. The issue never occurs if we get rid of this line, or modify it so that $index is cleared before the second ok() line.

The second ok() seems to trigger the bug, to be specific we know that the scalar with the refcount mentioned in the warning is the one being created and blessed here:

https://github.com/Test-More/test-more/blob/stream/master/lib/Test/Stream/Context.pm#L263

Knowing that does not help us much. This same code runs with no problems if $index is destroyed before it runs. Making any significant changed to this method, or the methods leading up to it in the stack seem to effect the frequency at which the bug occurs, but will not eliminate it completely (This initially had us following a red herring where localizing $_ seemed to remove the problem, but that ultimately turned out to be incorrect).

So far we have only been able to reproduce this with any reliability on darwin, using perls 5.20.2 and 5.20.1. Alh managed to reproduce it at least once on linux, but it is not frequent enough to really dig in. 5.18.4 and earlier do not appear to reproduce the issue at all. I have not been able to try 5.20.0 or blead, and I do not expect to have the resources to do so in the near-term (I do not have a darwin box, and the one I have been using is being used for other things by its owner).

There are many other things that can be done to alter the frequency, in some cases enough so to make the problem appear solved, but ultimately it seems that the more state you have built up and stored, the more likely the issue is to occur.

**Comment by dagolden** [comment] 2015-05-02 17:50
FWIW, here's what $index was on a run with the error:

```
ok 1
SV = IV(0x7fdf878be840) at 0x7fdf878be850
  REFCNT = 1
  FLAGS = (PADMY,ROK)
  RV = 0x7fdf85a8c988
  SV = PVHV(0x7fdf878ad020) at 0x7fdf85a8c988
    REFCNT = 1
    FLAGS = (SHAREKEYS,HASKFLAGS)
    ARRAY = 0x7fdf83d7d530  (0:4, 1:4)
    hash quality = 137.5%
    KEYS = 4
    FILL = 4
    MAX = 7
    Elt "ns" [UTF8 "ns"] HASH = 0x882586a
    SV = PV(0x7fdf878d3800) at 0x7fdf85a8ca18
      REFCNT = 1
      FLAGS = (POK,pPOK,UTF8)
      PV = 0x7fdf83d514f0 "test.test_collection"\0 [UTF8 "test.test_collection"]
      CUR = 20
      LEN = 22
    Elt "key" [UTF8 "key"] HASH = 0xbe83d6b4
    SV = IV(0x7fdf85a8c9d8) at 0x7fdf85a8c9e8
      REFCNT = 1
      FLAGS = (ROK)
      RV = 0x7fdf85a8c9b8
      SV = PVHV(0x7fdf878ad040) at 0x7fdf85a8c9b8
        REFCNT = 1
        FLAGS = (SHAREKEYS,HASKFLAGS)
        ARRAY = 0x7fdf862b86e0  (0:7, 1:1)
        hash quality = 100.0%
        KEYS = 1
        FILL = 1
        MAX = 7
        Elt "x.y" [UTF8 "x.y"] HASH = 0x56c322f9
        SV = IV(0x7fdf85a8c9c0) at 0x7fdf85a8c9d0
          REFCNT = 1
          FLAGS = (IOK,pIOK)
          IV = 1
    Elt "name" [UTF8 "name"] HASH = 0xcb7b6dbd
    SV = PV(0x7fdf878d37f0) at 0x7fdf85a8ca00
      REFCNT = 1
      FLAGS = (POK,pPOK,UTF8)
      PV = 0x7fdf83d807c0 "foo"\0 [UTF8 "foo"]
      CUR = 3
      LEN = 10
ok 2
1..2
Attempt to free unreferenced scalar: SV 0x7fdf8419a870, Perl interpreter: 0x7fdf85000000 during global destruction.
```

**Comment by dagolden** [comment] 2015-05-03 14:53
To any following: my ongoing work on simplifying and reproducing is here: https://github.com/dagolden/zzz-repro-test-stream-mongodb-bug

**Comment by ribasushi** [comment] 2016-04-23 10:45
@xdg has this been addressed by newer T::M versions or is it still a problem?

**Comment by xdg** [comment] 2016-04-23 13:48
I haven't had an opportunity to check.

**Comment by exodist** [comment] 2016-06-01 14:07
I would be surprised if this was still a problem. Closing for now. Please re-open if the problem happens again.

**Closed by exodist** 2016-06-01 14:07 UTC
