### ISSUE TITLE
Test::Simple: test failures 478-cmp_ok_hash.t on Solaris

### ISSUE THREAD

**Issue by weakcamel** [Test-More/test-more#530] opened 2014-12-31 11:49 UTC
The following test cases fail at Solaris (SunOS servername 5.10 Generic_137111-03 sun4u sparc SUNW,Netra-T12

```
ok 1 - Passes on correct comparison
ok 2 - Did not pass
ok 3 - 1 result
ok 4 - result is false
not ok 5 - Syntax error
#   Failed test 'Syntax error'
#   at t/478-cmp_ok_hash.t line 35.
#                   '    '0'
#         #eq
#     '0'
# '
#     doesn't match '(?^:syntax error at \(eval in cmp_ok\))'
not ok 6 - We got warnings
#   Failed test 'We got warnings'
#   at t/478-cmp_ok_hash.t line 39.
1..6
# Looks like you failed 2 tests of 6.
```

Perl version / architecture details

```
 perl -V
Summary of my perl5 (revision 5 version 20 subversion 1) configuration:

  Platform:
    osname=solaris, osvers=2.10, archname=sun4-solaris-thread-multi
    uname='sunos il02build03 5.10 generic_137111-03 sun4u sparc sunw,netra-t12 '
    config_args='-des -Dprefix=/perl/path -Dcc=gcc -Dusethreads -Duserelocatableinc -Dusesitecustomize'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DPERL_USE_SAFE_PUTENV',
    optimize='-O',
    cppflags='-D_REENTRANT -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='3.3 (RL)', gccosandvers='solaris2.10'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib '
    libpth=/apps/public/gcc_3.3/lib /usr/lib /usr/local/lib /usr/ccs/lib
    libs=-lsocket -lnsl -ldl -lm -lpthread -lc
    perllibs=-lsocket -lnsl -ldl -lm -lpthread -lc
    libc=/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' -Wl,-E'
    cccdlflags='-fPIC', lddlflags=' -Wl,-E -shared -L/usr/local/lib'


Characteristics of this binary (from libperl):
  Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                        PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP
                        PERL_NEW_COPY_ON_WRITE PERL_PRESERVE_IVUV
                        PERL_USE_SAFE_PUTENV USE_ITHREADS USE_LARGE_FILES
                        USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
                        USE_REENTRANT_API USE_SITECUSTOMIZE
  Built under solaris
```

**Comment by weakcamel** [comment] 2015-01-01 09:21
Silly me :-) Indeed, forgot to write it. I was installing 1.001014, and I was installing it manually (through makefile) into a local Perl installation (local, i.e. in a specific prefix).

I did add some extra paths to @INC through sitecustomize.pl, however those were to subdirectories of the $PREFIX (legacy paths for some other modules).
I can check for other versions (I don't think there were any, but I'm not positive) once I'm back on that installation and and report back.

**Comment by exodist** [comment] 2015-01-03 21:55
@weakcamel I had a couple people with access to solaris check on this, they could not reproduce the problem. I still suspect it is an issue with your @INC management.

**Comment by karenetheridge** [comment] 2015-01-03 22:21
@weakcamel Could you please provide the exact command(s) you used to install or test the module?

**Comment by weakcamel** [comment] 2015-01-05 19:43
Hello,sorry it took a while.
I checked again and you were right. I had 2 different versions of a few packages installed in separate locations, including Test::Simple, and @INC was pointing at the wrong one (I was doing multiple installations/upgrades of a series of modules, and there must have been some leftovers). 
So, not an issue. Thanks for your help! I promise to double-check before submission next time! :-)

**Comment by exodist** [comment] 2015-01-05 19:50
No problem, better to have a mistake reported than to have a real issue go unreported. Closing.

**Closed by exodist** 2015-01-05 19:50 UTC
