### ISSUE TITLE
"my" variable … masks earlier declaration in same scope

### ISSUE THREAD

**Issue by daxim** [Test-More/test-more#849] opened 2020-03-06 20:01 UTC
Repro
-----

    perl -e'use Kavorka; use Test::More import => [qw(diag done_testing)]; use Test::Deep qw(cmp_set);'

Result
-----

    "my" variable $count masks earlier declaration in same scope at …/Test2/Hub.pm line 355.
    "my" variable $ok masks earlier declaration in same scope at …/Test/More.pm line 568.
    "my" variable $cmp masks earlier declaration in same scope at …/Test/Deep.pm line 439.

Expected
-----

No warnings.

Versions
-----

    › perl -mTest2::Hub -E'say Test2::Hub->VERSION'
    1.302171
    › perl -mTest::More -E'say Test::More->VERSION'
    1.302171
    › perl -mTest::Deep -E'say Test::Deep->VERSION'
    1.130

Patch
-----

```
diff --git a/Test/Deep.pm b/Test/Deep.pm
index e8c332e..69fa9a9 100644
--- a/Test/Deep.pm
+++ b/Test/Deep.pm
@@ -428,16 +428,15 @@ sub wrap
   my $class = Scalar::Util::blessed($data);
   return $data if defined $class and $data->isa("Test::Deep::Cmp");
 
+  my $cmp;
   if (defined $class and $data->can('as_test_deep_cmp')) {
-    my $cmp = $data->as_test_deep_cmp;
+    $cmp = $data->as_test_deep_cmp;
     return $cmp if $cmp->isa('Test::Deep::Cmp');
     Carp::confess("object in expected structure provides as_test_deep_cmp but it did not return a Test::Deep::Cmp");
   }
 
   my $reftype = _td_reftype($data);
 
-  my $cmp;
-
   if($reftype eq '')
   {
     $cmp = $Test::Deep::LeafWrapper
diff --git a/Test/More.pm b/Test/More.pm
index 72f6152..d010d6e 100644
--- a/Test/More.pm
+++ b/Test/More.pm
@@ -545,14 +545,15 @@ sub can_ok ($@) {
     my $class = ref $proto || $proto;
     my $tb = Test::More->builder;
 
+    my $ok;
     unless($class) {
-        my $ok = $tb->ok( 0, "->can(...)" );
+        $ok = $tb->ok( 0, "->can(...)" );
         $tb->diag('    can_ok() called with empty class or reference');
         return $ok;
     }
 
     unless(@methods) {
-        my $ok = $tb->ok( 0, "$class->can(...)" );
+        $ok = $tb->ok( 0, "$class->can(...)" );
         $tb->diag('    can_ok() called with no methods');
         return $ok;
     }
@@ -565,7 +566,7 @@ sub can_ok ($@) {
     my $name = (@methods == 1) ? "$class->can('$methods[0]')" :
                                  "$class->can(...)"           ;
 
-    my $ok = $tb->ok( !@nok, $name );
+    $ok = $tb->ok( !@nok, $name );
 
     $tb->diag( map "    $class->can('$_') failed\n", @nok );
 
diff --git a/Test2/Hub.pm b/Test2/Hub.pm
index c08f276..be1423e 100644
--- a/Test2/Hub.pm
+++ b/Test2/Hub.pm
@@ -329,8 +329,9 @@ sub process {
 
     # Optimize the most common case
     my $type = ref($e);
+    my $count;
     if ($type eq 'Test2::Event::Pass' || ($type eq 'Test2::Event::Ok' && $e->{pass})) {
-        my $count = ++($self->{+COUNT});
+        $count = ++($self->{+COUNT});
         $self->{+_FORMATTER}->write($e, $count) if $self->{+_FORMATTER};
 
         if ($self->{+_LISTENERS}) {
@@ -352,7 +353,7 @@ sub process {
     $self->{+_PASSING} = 0 if $fail;
 
     my $code = $f->{control}->{terminate};
-    my $count = $self->{+COUNT};
+    $count = $self->{+COUNT};
 
     if (my $plan = $f->{plan}) {
         if ($plan->{skip}) {
```

**Comment by exodist** [comment] 2020-03-06 21:02
I cannot reproduce. Also, if anything this is a bug in Kavorka if it breaks downstream modules like that. If you could reproduce the issue without Kavorka that would be something.

**Comment by jkeenan** [comment] 2020-03-06 21:49
> I cannot reproduce. 

Nor can I reproduce.

```
[ef0d5f5f6] 613 $ ./bin/perl -v | head -2 | tail -1
This is perl 5, version 31, subversion 9 (v5.31.9 (v5.31.8-157-gef0d5f5f6f)) built for x86_64-linux-quadmath
[ef0d5f5f6] 614 $ ./bin/perl -Ilib -mTest::More -E'say Test::More->VERSION'
1.302171
[ef0d5f5f6] 615 $ ./bin/perl -Ilib -mTest2::Hub -E'say Test2::Hub->VERSION'
1.302171
[ef0d5f5f6] 616 $ ./bin/perl -Ilib -mTest::Deep -E'say Test::Deep->VERSION'
1.130
[ef0d5f5f6] 617 $ ./bin/perl -Ilib -we'use Kavorka; use Test::More import => [qw(diag done_testing)]; use Test::Deep qw(cmp_set);'
[ef0d5f5f6] 618 $ [ no output ]
```

**Comment by exodist** [comment] 2020-03-06 22:02
Closing as I do not think there is actually a bug here for this repo. IF there is a bug it is Kavorka, but it sounds like it might actually be a broken perl on the reporters end.

**Closed by exodist** 2020-03-06 22:02 UTC

**Comment by karenetheridge** [comment] 2020-03-10 17:35
I am curious to find out what peculiar things Kavorka is doing to the parser to cause this.
