### ISSUE TITLE
Test2::Event::Exception & IPC issues

### ISSUE THREAD

**Issue by autarch** [Test-More/test-more#790] opened 2017-09-29 19:05 UTC
I had an interesting issue today with the combo of an Exception event and IPC. The Exception event contained an exception, which in turn contained a `Specio::Constraint::Simple` object, which in turn contains several code references.

When the IPC code attempted to serialize the Exception event, it blew up because Storable cannot store coderefs.

I could imagine this happening pretty easily with other types of exceptions that might capture objects related to the exception.

I don't have any good ideas for how Test2 might ameliorate this problem, but I figured it was at least worth noting as an issue.

**Comment by exodist** [comment] 2017-09-29 19:12
I encountered this problem as well. I *thought* I had made it so that exceptions were stringified for serialization, apparently I only did that in the Stream formatter, and not in the IPC system itself. I will fix that at some point. I do not think it is reasonable to expect complex exceptions to go through the IPC system intact.

**Comment by autarch** [comment] 2017-09-29 19:17
Forcing stringification seems fine, as long as it's documented.

**Comment by exodist** [comment] 2017-10-01 06:11
This is a duplicate of #756

**Comment by exodist** [comment] 2017-10-01 06:44
* related, not duplicate.

**Closed** 2017-10-03 02:34 UTC
