### ISSUE TITLE
Test2::API assumes that stdout implements fileno

### ISSUE THREAD

**Issue by choroba** [Test-More/test-more#809] opened 2018-05-11 16:24 UTC
If stdout is tied to a module that doesn't implement `FILENO` (which is mentioned as optional in *perltie*), using anything that uses `Test2::API` (for example `Test::MockObject`) dies, as `Test2::API` calls `clone_io` from `Test2::Util`.

How to reproduce:
--

Library:

```
package MyStdout;

use parent 'Tie::Handle';

my $stdout;
BEGIN {
    use IO::Handle;
    $stdout = 'IO::Handle'->new_from_fd(1, 'w');
}

sub TIEHANDLE { my $i; bless \$i, shift }

sub PRINT {
    shift;
    print {$stdout} "BEGIN:\n", @_, "END.\n";
}

# This fixes the error, but is it correct?
# sub FILENO { undef }

tie *STDOUT, 'MyStdout';

1
```

Script:

```
#!/usr/bin/perl
use warnings;
use strict;

use MyStdout;

# Uncomment the following line to trigger the error:
# use Test::MockObject;

print "Hello, world!\n";
```

**Comment by pali** [comment] 2018-06-12 07:53
Probably you want to return `-1` from `FILENO`. `undef` should be returned when filehandle is not open.

**Comment by exodist** [comment] 2018-12-04 22:08
This is easily solved by this patch:
```
 sub clone_io {
     my ($fh) = @_;
-    my $fileno = fileno($fh);
+    my $fileno = eval { fileno($fh) };
```

But the patch does not sit well with me. This could easily mask an error where fileno has an implementation bug and throws a real exception. The next logical step in that argument is to have it warn, but the warning is just as mucha  problem, and sometimes would be fatal anyway. Another option is to check the exception to see if it is this specific exception, but that masks if someone forgot to implement FILENO when they intended to.

Ultimately I do not feel like this is something Test2 should address. I think having it die with the current exception, allowing the person who gets it to debug it as you have, is the correct action. I am going to close this as not a bug. I think the proper solution is to implement FILENO. There are known options for a negative or undef fileno, but the expectation that you can call fileno on a handle should not be broken, when it is broken that is something Test2 does not handle.

**Closed by exodist** 2018-12-04 22:08 UTC

**Comment by choroba** [comment] 2018-12-05 08:20
In other words, if you want to test a tied handle, FILENO is no longer optional.
