### ISSUE TITLE
DROLSKY/Test-Vars-0.008.tar.gz fails with 1.302013_005

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#619] opened 2016-01-02 23:15 UTC
http://www.cpantesters.org/cpan/report/63782227

**Comment by exodist** [comment] 2016-01-03 06:52
I have a patch to fix this, but it is currently part of a bigger patch. I will close this ticker either when I merge the bigger patch, or when I split the patch to pull in the relevant bits.

The problem is a Test::Tester issue where its Test::Builder::XXX overrides do not obtain contexts.

**Comment by exodist** [comment] 2016-01-04 04:05
Fixed in Test2/master

**Closed by exodist** 2016-01-04 04:05 UTC
Labels: Blocking Stable, Bug, Easy, HasPatch, Test-Stream
