### ISSUE TITLE
$hid can be undef

### ISSUE THREAD

**Issue by philiprbrenan** [Test-More/test-more#882] opened 2021-05-13 19:37 UTC
In file: 5.30.0/Test2/API.pm

**$hid** in the highlighted line 395 in the left hand window can easily be **undef** leading to the results seen in the right hand window.

![image](https://user-images.githubusercontent.com/7548378/118177697-f19a9d00-b42a-11eb-8d07-881c59cc7cac.png)

**Comment by exodist** [comment] 2021-05-13 20:09
Can you give me a reproduction script/test?  The intent was that a hub should never be missing an HID, the check for a hub above it should have prevented this. But if there is a (reasonable) cause for a hub to have no ID then the correct thing here might be to assign it one. I need to know the cause of the missing HID though before I can determine the right fix.

**Comment by exodist** [comment] 2023-04-27 14:44
@philiprbrenan I have submitted a PR. Please let me know if it sufficiently addresses your issue. If it does I can merge it, if not please provide me with more information about what would meet your expectations.

**Closed** 2023-10-24 17:24 UTC
