### ISSUE TITLE
Test2::Event::Skip does not define 'name'

### ISSUE THREAD

**Issue by karenetheridge** [Test-More/test-more#863] opened 2020-08-05 23:55 UTC
Test2::Event::Skip ISA Test2::Event::Ok, and ::Ok is documented as having a 'name' method, but name is not defined in the Skip object.  Should Skip really inherit from Ok?

I also noticed that when the 'skip' is generated through Test::Builder, `name` *is* defined (as the empty string) -- it is only when the skip is generated after Test2::Tools::Basic is loaded that `name` is undefined (even when Test::More::skip is used, bizarrely).

**Comment by exodist** [comment] 2020-08-06 04:30
I cannot reproduce the issue. For me `$skip->name` always returns the empty string `''`

```perl
use strict;
use warnings;

{
    package Foo;
    use Test2::Tools::Basic;
}

use Test::More;
use Test2::API qw/intercept/;

my $events = intercept {
    SKIP: {
        skip "skipme" => 1;
    }   
};

use Data::Dumper;
print Dumper($events);
print Dumper($events->[0]->name);

ok(1);

done_testing;
```
Output:
```
t/regression/863-skip_name.t .. 
$VAR1 = [
          bless( {
                   'name' => '',
                   'effective_pass' => 1,
                   '_eid' => '636401~0~1596688102~7',
                   'reason' => 'skipme',
                   'pass' => 1,
                   'hubs' => [
                               {
                                 'tid' => 0,
                                 'uuid' => undef,
                                 'pid' => 636401,
                                 'buffered' => 0,
                                 'hid' => '636401~0~1596688102~5',
                                 'nested' => 0,
                                 'details' => 'Test2::Hub::Interceptor',
                                 'ipc' => 0
                               }
                             ],
                   'trace' => bless( {
                                       'tid' => 0,
                                       'frame' => [
                                                    'main',
                                                    't/regression/863-skip_name.t',
                                                    14,
                                                    'Test::More::skip'
                                                  ],
                                       'hid' => '636401~0~1596688102~5',
                                       'pid' => 636401,
                                       'buffered' => 0,
                                       'cid' => '636401~0~1596688102~6',
                                       'nested' => 0
                                     }, 'Test2::EventFacet::Trace' )
                 }, 'Test2::Event::Skip' )
        ];
$VAR1 = '';
ok 1
1..1
```


Can you post the code you are seeing this issue with?

**Comment by karenetheridge** [comment] 2020-08-06 20:31
can no longer reproduce after updating; will reopen if this happens again

**Comment by karenetheridge** [comment] 2020-08-06 20:37
I closed this just a smidgen too soon!  the problem occurs with todo_skip:

```
use strict;
use warnings;

use Test2::API 'intercept';
use Test2::Tools::Basic ();
use Test::More 0.88;

my $events = intercept(sub {
  SKIP: {
    skip 'I want to skip some tests', 2;
    fail 'this is a failing test';
    pass 'this is a passing test';
  }

  TODO: {
    local $TODO = 'my todo message';
    #my $todo = todo('my todo message');
    fail 'this is a failing test that should todo';
    pass 'this is a passing test that should todo';

    todo_skip 'todoskip here', 1;
    fail 'this is a failing test that should todo_skip';
    pass 'this is a passing test that should todo_skip';
  }
});
use Data::Dumper;
local $Data::Dumper::Sortkeys = 1;
local $Data::Dumper::Maxdepth = 4;
#print STDERR "### events: ", Dumper($events);

foreach my $event (grep $_->can('name'), @$events) {
  print STDERR "### event has undefined name\n", Dumper($event)
    if not defined $event->name;
}

done_testing;
```

prints:

```
### event has undefined name
$VAR1 = bless( {
                 '_eid' => '45377~0~1596746242~16',
                 'effective_pass' => 1,
                 'hubs' => [
                             {
                               'buffered' => 0,
                               'details' => 'Test2::Hub::Interceptor',
                               'hid' => '45377~0~1596746242~5',
                               'ipc' => 0,
                               'nested' => 0,
                               'pid' => 45377,
                               'tid' => 0,
                               'uuid' => undef
                             }
                           ],
                 'pass' => 0,
                 'reason' => 'todoskip here',
                 'todo' => 'todoskip here',
                 'todo_diag' => 1,
                 'trace' => bless( {
                                     'buffered' => 0,
                                     'cid' => '45377~0~1596746242~15',
                                     'frame' => [
                                                  'main',
                                                  'repro.pl',
                                                  21,
                                                  'Test::More::todo_skip'
                                                ],
                                     'hid' => '45377~0~1596746242~5',
                                     'nested' => 0,
                                     'pid' => 45377,
                                     'tid' => 0
                                   }, 'Test2::EventFacet::Trace' )
               }, 'Test2::Event::Skip' );
1..0

```

**Comment by exodist** [comment] 2020-08-06 20:49
CAn you elaborate on what problem this causes for you? I sit simply an inconsistency in having the ->{name} attribute defined/undefined, or is there an error/bug you are trying to nail down?

a skipped test does not have a name because it was skipped, it is inconsistent that it is sometimes undefined, and sometimes an empty string, so yeah it should probably be made consistent. But is this causing actual pain/hardship?

**Comment by karenetheridge** [comment] 2020-08-06 21:07
I was doing something like this:

`my @tests = grep $_->isa('Test2::Event::Ok') && $_->name =~ /$test_name/, @$events;`

..to check that all the tests I expected to run did in fact run.

It's odd that a `skip` will generate a ::Skip object with a name (the skip reason is assigned to `name` as well as `reason`, but a `todo_skip` will generate one without it. I think Test::Builder treated skip and todo_skip very similarly (the only difference is one needs a SKIP label and the other needs a TODO label).

**Comment by exodist** [comment] 2020-08-06 21:22
actually I do recall the skip vs skip_todo being a big hairball where they had a lot of very subtle differences, and in my first pass I introduced a lot of test failures and bugs and had to go back to it a lot before Test2 was released. I would not be surprised if fixing this caused a lot of the legacy Test::Builder tests to fail, but I will have to go back and see. It is equally likely that I overlooked the name when fixing those bugs.

**Comment by karenetheridge** [comment] 2020-08-06 21:24
fwiw, I can easily do a `// ''` in my checks.. I just wanted to flag this for you in case something surprising was going on. I'm certainly not needing a fix here - I had some todo_skips in my test script while experimenting with how the intercepted events look, but I'm not using them in real code.

**Comment by exodist** [comment] 2023-04-27 14:48
closing as this seems to need no fix at this time.

**Closed by exodist** 2023-04-27 14:48 UTC

**Comment by karenetheridge** [comment] 2023-04-27 15:08
Only if you're confident that nothing strange is going on :)
