### ISSUE TITLE
Regression from 1.001014: DESTROY { system('false') }

### ISSUE THREAD

**Issue by powerman** [Test-More/test-more#807] opened 2018-04-03 20:44 UTC
If test has `DESTROY{}` block which executes external command which return non-0 exit status then test will fail only with Test::More newer than 1.001014.

(In real world I've used such a DESTROY block to run some external command to cleanup before Path::Tiny::tempdir() will remove temporary directory even if test crashed while working in this directory.)

```sh
$ mkdir t
$ cat >t/skipall.t <<'EOF'
use Test::More;
my $guard = bless {};
sub DESTROY { system('false'); }
plan skip_all => 'some requirement is not met';
EOF

$ cpanm -q Test::More@1.001014
Successfully installed Test-Simple-1.001014 (downgraded from 1.302135)
1 distribution installed
$ prove -r
./t/skipall.t .. skipped: some requirement is not met
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
Result: NOTESTS

$ cpanm -q Test::More
Successfully installed Test-Simple-1.302135 (upgraded from 1.001014)
1 distribution installed
$ prove -r
./t/skipall.t .. # Looks like your test exited with 256 before it could output anything.
./t/skipall.t .. skipped: some requirement is not met

Test Summary Report
-------------------
./t/skipall.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.03 cusr  0.00 csys =  0.05 CPU)
Result: FAIL
```

**Comment by exodist** [comment] 2018-04-03 20:46
Thanks for the report, I will look into it as soon as I have a moment.

**Comment by exodist** [comment] 2018-04-19 17:16
I found where the problem is, and why the behavior changed. That said I suspect the old behavior was not intentional. The old behavior happened because Test::Builder decided a skip_all should exit 0. I do not think the intention was to make it mask other values of $? when set via destruction.

My preference would be to keep the current behavior as more-correct. I do not like the idea of intentionally masking errors. However I am open to changing my mind if you can make a compelling argument for the old behavior.

If you just want to fix your problem you can change your DESTROY block:

`sub DESTROY { local $?; system('false'); }`

**Comment by exodist** [comment] 2018-04-19 19:30
That is reasonable to me, I will see about improving that message.

**Comment by Leont** [comment] 2018-04-20 08:45
> That said I suspect the old behavior was not intentional.

It's a rather non-obvious "feature" that calling `system` after `exit` can override the return value of the program. I'd rather have $? be masked and if anyone really needs it a more explicit way to set the exit value.

**Comment by exodist** [comment] 2018-12-04 22:15
Marking as low priority, this is not a common problem, and the correct answer is not clear. I want some more input before deciding on a final solution. Maybe at the next PTS summit I will ask around.

**Comment by exodist** [comment] 2019-04-25 09:38
@Leont when you have a moment at the PTS this week please review this and then we can chat. The question is this:
Should a skip-all plan always force the exit value to be 0, even if something else tries to set an exit value (intentionally or otherwise)?

**Comment by exodist** [comment] 2019-04-25 09:59
^ The above commit would fix this issue if I merge it. Just need to decide if it is a good idea or a bad idea to do this.

**Comment by exodist** [comment] 2019-04-25 10:13
Discussed this with @Leont, @haarg and a couple others at the PTS. We all agree that it could be argued either way, but nobody has a strong opinion. We have decided that since this new behavior has been in place so long with only 1 issue reported that we are gonna close the issue as wont-fix as the new behaviors is more "normal" for perl and the old behavior was likely unintentional.

**Closed by exodist** 2019-04-25 10:13 UTC
Labels: Discuss, Low Priority
